name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: maven package
      run: mvn clean package
    - name: Build the Docker image
      run: docker build ./ -t nft-tracker:${SHORT_SHA} --build-arg key=${{secrets.JASYPT_PASSWORD}} 
    - name: Push Docker image
      run: |
        docker image tag nft-tracker:${SHORT_SHA} scratchmaster/nft-tracker:${SHORT_SHA}
        docker image push scratchmaster/nft-tracker:${SHORT_SHA}
